### PR TITLE
Drop Ruby 2.4 support 💎

### LINKED ISSUE #125: Consider dropping support for unmaintained Ruby releases
The gem requires Ruby >= 2.4

https://github.com/sunny/actor/blob/0c8717e24b22d2d9a7d791cccfd09529fcee2bfd/service_actor.gemspec#L35

but that versions EOLed 3 years ago, I'd suggest to bump `required_ruby_version` to `>= 3.0` or at least `>= 2.7'

### PR DESCRIPTION
**Pull request by sunny**
Closes #125

### CODE REVIEW

**Comment by sunny** [comment]
@pboling Any idea why this is complaining about a missing `rspec-block_is_expected` gem when using a different Rubocop LTS version? 🤔

**Comment by pboling** [comment]
@sunny yes, that's a bug.  `rspec-block_is_expected` is a tiny RSpec plugin I wrote, and use on every project, and as such I sometimes fail to notice when I've made it an undeclared dependency.

I'll have a fix out soon!

**Comment by pboling** [comment]
Ref: https://github.com/pboling/rspec-block_is_expected

**Comment by sunny** [comment]
@pboling Also the `rubocop-gradual` is included in `rubocop-ruby2_7`. Unless I’m misunderstanding this, it changes the workflow of the projects using `rubocop-lts`, as they now *have* to use rubocop-gradual.

**Comment by pboling** [comment]
@sunny https://github.com/rubocop-lts/standard-rubocop-lts/blob/main/CHANGELOG.md#1010-2024-03-23 I've released a new version of `standard-rubocop-lts`, which all of the rubocop-lts family of gems depend on, which band-aids that missing dependency.  I'll have a direct fix later.

**Pull request merged**
